In [1]:
import numpy as np

In [3]:
np.array([2,5,8,66])

array([ 2,  5,  8, 66])

In [4]:
a=np.array([2,455,38,5])  #vector
print(a)

[  2 455  38   5]


In [5]:
type(a)

numpy.ndarray

In [6]:
#2d array(matrix)

new =np.array([[45,55,2,28],[36,54,66,4]])
print(new)

[[45 55  2 28]
 [36 54 66  4]]


In [11]:
#3d array
np.array ([[22,54,26,84],[48,57,5,6],[28,65,54,7],[57,68,94,55]])

array([[22, 54, 26, 84],
       [48, 57,  5,  6],
       [28, 65, 54,  7],
       [57, 68, 94, 55]])

In [13]:
np.array([11,5,88] , dtype =float)

array([11.,  5., 88.])

In [15]:
np.array([0,23,53] ,dtype =bool)

array([False,  True,  True])

In [17]:
np.array([58,64,5] ,dtype =complex)

array([58.+0.j, 64.+0.j,  5.+0.j])

In [19]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
np.arange(1,25,3) #strides --> alternative nos

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [23]:
np.arange(1,10) .reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
rand(2,3)
random.rand(2,3)

NameError: name 'rand' is not defined

In [ ]:
np.random.rand(5)

In [ ]:
np.random.randint(2,4)

In [29]:
np.random.randint(2,20)

3

In [31]:
np.random.randint(10,20,5)

array([18, 14, 11, 16, 14])

In [33]:
np.random.randint(0,1)

0

In [35]:
np.random.randint(-30,20,10)

array([ 18, -18, -23,  16, -30,  -3, -25,  -3,  18, -28])

In [37]:
np.random.randint(0,40,(10,10))

array([[37, 13, 12, 32,  6, 25, 13, 36, 15, 35],
       [28, 13, 18, 31, 33,  8, 14, 30, 15, 38],
       [ 1,  4, 34, 20, 29, 26, 28, 26, 18,  9],
       [37, 18,  8, 16, 32,  7, 27,  9,  6, 15],
       [ 9, 31, 39, 37, 25,  5, 14, 37,  9, 21],
       [ 0, 10, 39, 36, 13, 17, 19, 23, 10, 27],
       [33, 34, 35, 38,  4, 25, 13,  0, 14, 12],
       [37,  1,  5, 32,  3, 10,  6, 13, 27, 29],
       [36,  4, 36, 34, 31,  3, 10, 14, 26, 14],
       [28, 24, 17,  1, 38, 18,  4, 24, 21, 31]])

In [39]:
np.arange(1,12).reshape(11,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [41]:
b = np.random.randint(10,20,(5,4))
b

array([[14, 12, 14, 19],
       [15, 11, 10, 19],
       [14, 16, 17, 12],
       [19, 11, 17, 13],
       [14, 16, 18, 19]])

In [47]:
type(b)

numpy.ndarray

In [49]:
#SLICING

In [51]:
b[1:3]

array([[15, 11, 10, 19],
       [14, 16, 17, 12]])

In [53]:
b

array([[14, 12, 14, 19],
       [15, 11, 10, 19],
       [14, 16, 17, 12],
       [19, 11, 17, 13],
       [14, 16, 18, 19]])

In [55]:
b[1:2]

array([[15, 11, 10, 19]])

In [57]:
b[1,3]

19

In [59]:
b[1,-1]

19

In [61]:
b

array([[14, 12, 14, 19],
       [15, 11, 10, 19],
       [14, 16, 17, 12],
       [19, 11, 17, 13],
       [14, 16, 18, 19]])

In [63]:
b[2:3]

array([[14, 16, 17, 12]])

In [65]:
b[3:4]

array([[19, 11, 17, 13]])

In [67]:
b[0:1]

array([[14, 12, 14, 19]])

In [69]:
b[0:-2]

array([[14, 12, 14, 19],
       [15, 11, 10, 19],
       [14, 16, 17, 12]])

In [71]:
b[0:-3]

array([[14, 12, 14, 19],
       [15, 11, 10, 19]])

In [73]:
b[-5,-3]

12

In [75]:
b[-4,2]

10

In [77]:
b[-4:2]

array([[15, 11, 10, 19]])

In [79]:
a = np.random.randint(10,20,(10,10))
a

array([[16, 18, 19, 11, 13, 10, 16, 11, 15, 12],
       [12, 14, 16, 16, 19, 16, 14, 12, 13, 10],
       [14, 15, 16, 13, 11, 11, 11, 19, 15, 13],
       [14, 18, 10, 12, 11, 11, 16, 18, 13, 14],
       [17, 12, 16, 11, 10, 17, 17, 16, 15, 15],
       [15, 15, 11, 12, 16, 18, 16, 17, 12, 17],
       [10, 12, 11, 15, 12, 15, 17, 18, 12, 11],
       [14, 18, 16, 14, 19, 14, 12, 19, 14, 14],
       [17, 19, 14, 15, 18, 18, 17, 11, 11, 10],
       [13, 12, 14, 12, 18, 19, 17, 16, 11, 11]])

In [81]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
#linespace

In [87]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [89]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

In [91]:
np.linspace(-3,9,5)

array([-3.,  0.,  3.,  6.,  9.])

In [93]:
#Identity #creating the identity matrix

In [95]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [97]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [99]:
#array attributes

In [101]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
a2 = np.arange(12, dtype =float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [105]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [107]:
#ndim

In [109]:
a1.ndim

1

In [111]:
a2.ndim

2

In [113]:
#shape

In [115]:
a1.shape

(10,)

In [117]:
a2.shape #3 rows and 2 columns

(3, 4)

In [119]:
a3.shape # first ,2 saysit consists of 2d arrays 2,2 gives no of rows

(2, 2, 2)

### size #gives no of items

In [122]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [124]:
a3.size
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [126]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [128]:
a2.size

12

In [130]:
# item size ....memory occupied by item

In [132]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [136]:
a1.itemsize #bytes

4

In [138]:
a2.itemsize

8

In [140]:
a3.itemsize

4

In [142]:
#dtype

In [144]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


In [146]:
#changing dtype

In [148]:
x =np.array([33,65,88])
x

array([33, 65, 88])

In [150]:
x.astype(int)

array([33, 65, 88])

In [152]:
#array operations

In [154]:
n1 =np.arange(12).reshape(3,4) 
n2 =np.arange(12,24).reshape(3,4)
n2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [156]:
n1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [158]:
#indexing & slicing

In [160]:
p1 =np.arange(10)
p2 =np.arange(12).reshape(3,4)
p3 =np.arange(8).reshape(2,2,2)

In [162]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [164]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [166]:
#1d array

In [168]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
p1[-1]

9

In [172]:
p1[5]

5

In [174]:
#2d array

In [176]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
p2[1,2]

6

In [180]:
p2[2,3]

11

In [182]:
p2[1,0]

4

In [184]:
#indexing 3d array

In [186]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [188]:
p3[1,0,1]

5

In [190]:
p3[1,0,0]

4

In [192]:
p3[0,1,1]

3

In [194]:
p3[1,1,0]

6

In [196]:
p3[0,0,1]

1

In [198]:
p3[0,0,0]

0

In [200]:
# slicing on 1d

In [202]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [213]:
p1[2:5]

array([2, 3, 4])

In [215]:
p1[1:4]

array([1, 2, 3])

In [ ]:
#slicing on 2D

In [217]:
p1[2:5:2]

array([2, 4])

In [219]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [221]:
p2[0,2]

2

In [235]:
p2[:,2] # all rows so(:),and we want 3rdcolumn so 2

array([ 2,  6, 10])

In [237]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [239]:
p2[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [241]:
p2[1:3 , 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [243]:
p2[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [245]:
p2[::2, ::3]

array([[ 0,  3],
       [ 8, 11]])

In [247]:
p2[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [249]:
p2[0:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [251]:
p2[0:2 ,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [253]:
p2[0:2 ,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
#slicing in 3d

In [257]:
p3 =np.arange(27).reshape(3,3,3) 
p3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [261]:
p3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [263]:
p3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [265]:
p3[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [269]:
p3[0,2,:]

array([6, 7, 8])

In [273]:
p3[1,:,1]

array([10, 13, 16])

In [275]:
p3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [279]:
 p3[2, 1:]

array([[21, 22, 23],
       [24, 25, 26]])

In [281]:
p3[2, 1: ,1:]

array([[22, 23],
       [25, 26]])

In [283]:
p3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [285]:
p3[0::2 ,0]

array([[ 0,  1,  2],
       [18, 19, 20]])

In [291]:
p3[0::2 ,0 ,::2]

array([[ 0,  2],
       [18, 20]])