In [5]:
import numpy as np

In [7]:
np.array([2,5,8,66])

array([ 2,  5,  8, 66])

In [9]:
a=np.array([2,455,38,5])  #vector
print(a)

[  2 455  38   5]


In [11]:
type(a)

numpy.ndarray

In [15]:
#2d array(matrix)

new =np.array([[45,55,2,28],[36,54,66,4]])
print(new)

[[45 55  2 28]
 [36 54 66  4]]


In [19]:
#3d array
np.array ([[22,54,26,84],[48,57,5,6],[28,65,54,7],[57,68,94,55]])

array([[22, 54, 26, 84],
       [48, 57,  5,  6],
       [28, 65, 54,  7],
       [57, 68, 94, 55]])

In [21]:
np.array([11,5,88] , dtype =float)

array([11.,  5., 88.])

In [23]:
np.array([0,23,53] ,dtype =bool)

array([False,  True,  True])

In [25]:
np.array([58,64,5] ,dtype =complex)

array([58.+0.j, 64.+0.j,  5.+0.j])

In [27]:
np.arange(1,25)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [33]:
np.arange(1,25,3) #strides --> alternative nos

array([ 1,  4,  7, 10, 13, 16, 19, 22])

In [47]:
np.arange(1,11) .reshape(4,2)

ValueError: cannot reshape array of size 10 into shape (4,2)